name: Build
on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Install prerequisites
        run: ci/install.sh
      - name: Upgrade Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM install
        run: npm ci
      - name: Build
        run: source emsdk/emsdk_env.sh && ./build.sh
      - name: Bundle
        run: npm run build
      - name: Test
        run: npm test
      - name: Package
        run: npm pack
      - name: Publish to npm
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
