name: Compile

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Setup emsdk
              uses: mymindstorm/setup-emsdk@476bc50c4df2db1a3e9d72df0885c43ae0e5a3d4
            - uses: actions/checkout@v1
            - name: Build
              run: |
                  ./build.sh
                  sha256sum ./dist/argon2.js >> ./dist/CHECKSUM
                  sha256sum ./dist/argon2.wasm >> ./dist/CHECKSUM
            - name: Upload artifacts
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: dist
                  path: ./dist
